### ISSUE TITLE
class.upload.php official repo

### ISSUE THREAD

**Issue by verot** [petitp/verot-upload#1]
Thank you for your repository, and the Composer support.

I have set up an official repository for class.upload.php, with Composer support, but without psr-0 support yet.
https://github.com/verot/class.upload.php

You may want to discontinue your repository.

**Comment by andrejhudec** [comment]
I have updated the readme file. Thanks for your feedback.

**Comment by verot** [comment]
Hello. Thank you. But I think you may want to update the README, as the link you put in it is the link back to your own repository.

**Comment by andrejhudec** [comment]
Fixed.
